# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [2]:
import numpy as np

## Task 1
- print version of numpy

In [2]:
print(np.__version__)

1.16.4


## Task 2
- create 1d vector of zeros of size 10

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Task 3
- create 1d vector filled with ones of size 10

In [5]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Task 4
- create 1d vector filled with ones of size 10,

In [6]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [9]:
x=np.arange(1,11)
print("The matrix is {}".format(x))
print("The reversed matrix is {}".format(x[-1:0:-1]))

The matrix is [ 1  2  3  4  5  6  7  8  9 10]
The reversed matrix is [10  9  8  7  6  5  4  3  2]


## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [16]:
np.ones(9,dtype=int).reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Task 9
- create 3x3 matrix filled with random numbers

In [23]:
import random
np.random.randint(20,100, size=(3,3))

array([[53, 65, 37],
       [93, 82, 25],
       [55, 39, 51]])

## Task 10
- create 3x3x3 array filled with random numbers

In [24]:
np.random.randint(20,100, size=(3,3,3))

array([[[82, 79, 70],
        [76, 73, 74],
        [64, 81, 92]],

       [[71, 27, 88],
        [90, 62, 23],
        [64, 32, 23]],

       [[38, 79, 51],
        [31, 49, 42],
        [91, 29, 35]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [10]:
x=np.random.randint(20,100, size=(10,10))
print(x)
print("")
print("Biggest number is {}".format(x.max()))
print("Lowest element is {}".format(x.min()))

[[78 45 57 47 69 92 55 85 92 33]
 [27 48 23 22 29 69 44 59 94 88]
 [94 28 35 84 50 48 97 89 32 37]
 [83 27 94 99 42 95 72 37 39 90]
 [26 30 74 32 73 41 72 77 86 98]
 [87 58 84 65 92 40 26 91 62 36]
 [58 50 32 53 86 82 75 53 30 57]
 [39 20 75 94 70 86 21 77 88 91]
 [46 95 67 56 88 91 20 90 97 34]
 [27 86 75 84 49 66 81 94 29 39]]

Biggest number is 99
Lowest element is 20


## Task 12
- create a random 1d vector of size 30 and find average of them

In [34]:
x=np.random.randint(1,100,size=30)
print("Vector of size 30 is {}".format(x))
print("")
print("The average value of vector is {:0.2f}".format(x.mean()))

Vector of size 30 is [71 25 21 25 64 49 34 95 57 17 47 11 46 95 98 47 80  9 92 67  1 99 16 65
 16  5 38 40 93 42]

The average value of vector is 48.83


## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [39]:
x=np.ones(25,dtype=int).reshape(5,5)
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [40]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [25]:
x=np.array([0,1])
y=np.array([1,0])
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [42]:
x=np.random.randint(10,100,size=(5,3))
y=np.random.randint(10,100,size=(3,2))
np.dot(x,y)

array([[10027,  3267],
       [13444,  5682],
       [ 9548,  4155],
       [12594,  4164],
       [11814,  4521]])

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [47]:
x=np.random.randint(0,11,size=100)
for i in range(len(x)):
    if(3<x[i]<8):
        x[i]=-x[i]
        
print(x)

[-6  3 -5 -7 -4 -5  0  9  1  3  2  2  8 -7 -6  1  1  0 10 -7  9  1 -7  9
 -6  8 10  3 -4 -7  8 -6  2 -5  0  1 -4 -7 10 -4  3 -7 10 -7 -5 -4  1  2
  0  3 -7 -4  9 -7 -4  8  9 -4  8  3  0  9 10 -6 -4 -6  1 -5  2 10  2  2
  0 -6  9 -7  2 -4  3  3 -6 10 10  2  0 -6  9  3  8 -6  1 -6  1 -4  3  1
  8  1  1  8]


## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [48]:
x=np.arange(0,5)
np.tile(x,5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [52]:
np.random.rand(100)

array([0.96207223, 0.76517262, 0.78856056, 0.55446817, 0.41299869,
       0.44238774, 0.47331256, 0.96062652, 0.05674427, 0.0696935 ,
       0.73822316, 0.95061331, 0.5473619 , 0.58914087, 0.59483043,
       0.38140391, 0.15854097, 0.15211272, 0.2799629 , 0.04205178,
       0.29138266, 0.31531163, 0.73113105, 0.53626804, 0.39536615,
       0.70732982, 0.03374347, 0.15915929, 0.23884664, 0.25547006,
       0.29026339, 0.68056891, 0.22936859, 0.67261756, 0.01861462,
       0.96928684, 0.01930068, 0.5544182 , 0.00686983, 0.91495194,
       0.93716921, 0.89259908, 0.6726128 , 0.16693359, 0.3346175 ,
       0.81907435, 0.69867463, 0.05789783, 0.84867203, 0.71174485,
       0.79682583, 0.167096  , 0.65080761, 0.30135738, 0.6732929 ,
       0.97994965, 0.40920274, 0.21831916, 0.35466612, 0.80171912,
       0.48533058, 0.27262614, 0.43079441, 0.53679103, 0.41674127,
       0.03021178, 0.11925882, 0.37392904, 0.77250308, 0.98126087,
       0.82071096, 0.98458049, 0.18889596, 0.16972753, 0.37268

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [42]:
x=np.random.randint(100,size=(10,2))
print(x)
a=x[:,0]
b=x[:,1]
c=np.sqrt(a**2+b**2)
print(c)
t=np.arctan(b/a)
print(t)

[[82 54]
 [67 95]
 [53 80]
 [92 49]
 [75  6]
 [80 82]
 [31 78]
 [ 6 21]
 [24 98]
 [37 11]]
[ 98.18350167 116.24973118  95.96353474 104.23531072  75.23961722
 114.56002793  83.93449827  21.84032967 100.89598605  38.60051813]
[0.58235295 0.95654677 0.98568389 0.48939299 0.07982999 0.79774322
 1.19250234 1.29249667 1.33062532 0.28897541]


## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [65]:
x=np.random.randint(10,100,size=(13,13))
print("Matrix is:\n{}".format(x))
t=np.where(x==x.max())
print("\nMaximal element at position {}".format(list(zip(t[0]+1,t[1]+1))))
x[t]=0
print("\nNew matrix is:\n{}".format(x))

Matrix is:
[[71 81 18 83 22 12 61 91 75 42 60 91 83]
 [94 64 10 37 17 81 73 77 43 96 17 37 23]
 [77 20 88 31 10 63 15 68 79 15 16 77 65]
 [88 53 73 22 66 21 79 67 16 86 17 16 16]
 [86 59 73 30 49 62 29 34 22 24 45 17 26]
 [32 55 45 83 26 91 11 41 52 46 52 71 13]
 [28 38 78 24 30 28 33 24 89 92 67 90 46]
 [13 87 67 35 75 79 31 39 32 38 28 47 59]
 [11 98 61 23 59 93 45 64 72 12 90 55 58]
 [11 16 24 13 53 44 31 15 35 83 17 58 47]
 [52 95 41 39 14 62 21 19 75 30 51 75 44]
 [30 98 75 52 19 69 76 79 90 66 41 42 96]
 [40 33 57 48 10 50 29 73 20 37 23 60 14]]

Maximal element at position [(9, 2), (12, 2)]

New matrix is:
[[71 81 18 83 22 12 61 91 75 42 60 91 83]
 [94 64 10 37 17 81 73 77 43 96 17 37 23]
 [77 20 88 31 10 63 15 68 79 15 16 77 65]
 [88 53 73 22 66 21 79 67 16 86 17 16 16]
 [86 59 73 30 49 62 29 34 22 24 45 17 26]
 [32 55 45 83 26 91 11 41 52 46 52 71 13]
 [28 38 78 24 30 28 33 24 89 92 67 90 46]
 [13 87 67 35 75 79 31 39 32 38 28 47 59]
 [11  0 61 23 59 93 45 64 72 12 90 55 58]
 

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [109]:
x=np.array(np.random.rand(10))
y=np.array(np.random.rand(10))
cauchym = np.array([[ 1.0/(x_i-y_j) for y_j in y] for x_i in x])
print(cauchym)

[[ 5.74618143e+00  2.42310101e+00 -1.24044724e+01 -1.62944763e+01
  -5.51950096e+01  2.64711262e+00  1.87991398e+00  2.53002417e+00
   1.43949572e+01 -2.05057646e+01]
 [ 3.75985129e+00  1.98163554e+00  8.83137478e+01  3.27130286e+01
   1.35461395e+01  2.12897569e+00  1.60287599e+00  2.05257679e+00
   6.19547507e+00  2.31628524e+01]
 [-4.29897307e+00  1.65234564e+02 -2.05229918e+00 -2.13669370e+00
  -2.35427127e+00 -3.46353835e+01  7.98104185e+00 -8.78027374e+01
  -2.96583181e+00 -2.19582797e+00]
 [-4.51768828e+00  5.77582365e+01 -2.10085425e+00 -2.18937549e+00
  -2.41838938e+00 -5.67837804e+01  7.32287055e+00 -7.83569643e+03
  -3.06831301e+00 -2.25150410e+00]
 [-7.94443867e+00  8.86591806e+00 -2.62799023e+00 -2.76798738e+00
  -3.14445224e+00  1.28423667e+01  4.30966865e+00  1.04876430e+01
  -4.33963623e+00 -2.86804464e+00]
 [-3.73997090e+00 -3.48237132e+01 -1.91561171e+00 -1.98893806e+00
  -2.17614617e+00 -1.57133198e+01  1.10462015e+01 -2.16650765e+01
  -2.68859410e+00 -2.04007878e+00

## Task 23
- create an array of random `float` numbers and convert it to `int`

In [75]:
x=np.random.uniform(10,20,10)
print("Float array:\n{}".format(x))
y=x.astype(int)
print("\nInt array:\n{}".format(y))

Float array:
[19.93647428 18.11311595 17.36511125 13.43983785 12.94981189 14.84603233
 18.30347867 14.17962372 19.32887244 18.63627485]

Int array:
[19 18 17 13 12 14 18 14 19 18]


## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [61]:
x=np.arange(16)
m=np.empty((4,4),dtype=int)

for i in range(4):
    for j in range(4):
        v=(np.random.choice(x,1,replace=False))
        x = np.delete(x, np.where(x == v))
        m[i,j]=v
        
m

array([[ 3, 15,  2,  1],
       [12, 13,  9,  7],
       [ 6,  8, 11, 10],
       [ 5,  4, 14,  0]])

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [46]:
x=np.random.randint(500,size=(5000)).reshape(100,50)
print("The original array is \n{}".format(x))
m=x.mean(axis=1)
for i in range(100):
    for j in range(50):
        x[i,j]=x[i,j]-m[i]
print("\nThe new array is\n{}".format(x))

The original array is 
[[ 61 424 247 ...  36 100 381]
 [294  25 212 ... 448 482 390]
 [140 356  37 ... 207 456 306]
 ...
 [332 103 310 ... 390  34 214]
 [257 358 493 ... 401 198 338]
 [485 242 252 ... 264 416 430]]

The new array is
[[-204  158  -18 ... -229 -165  115]
 [  55 -213  -26 ...  209  243  151]
 [-104  111 -207 ...  -37  211   61]
 ...
 [ 127 -101  105 ...  185 -170    9]
 [ -32   68  203 ...  111  -91   48]
 [ 194  -48  -38 ...  -26  125  139]]


## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [94]:
x=np.array(np.arange(100)).reshape(10,10)
print("The matrix is:\n{}".format(x))
print("\nThe diagonal elements are:{}".format(x.diagonal()))

The matrix is:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

The diagonal elements are:[ 0 11 22 33 44 55 66 77 88 99]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element

In [157]:
x=[1,2,3,4,5]
m=np.zeros(len(x)+((len(x)-1)*3),dtype=int)
m[0::4]=x
m

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [62]:
?np.all